DROP TABLE IF EXISTS TESTS;
DROP TABLE IF EXISTS QUESTIONS;

CREATE TABLE IF NOT EXISTS TESTS (
    TEST_ID SERIAL PRIMARY KEY,
    TEST_NAME varchar(50) NOT NULL,
    TYPE varchar(50),
    LEVEL varchar(2) CHECK(LEVEL IN ('A1','A2','B1', 'B2', 'C1', 'C2')) NOT NULL,
    QUESTIONS jsonb,
    CREATED_BY varchar(60)
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
  QUESTION_ID SERIAL PRIMARY KEY,
  TEST_ID INT REFERENCES TESTS(TEST_ID),
    QUESTION_TEXT VARCHAR(255),
    OPTIONS jsonb,
    CORRECT_ANSWER VARCHAR(255)
);

SELECT * FROM TESTS;
SELECT * FROM QUESTIONS;



